service: aws-python-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
            - dynamodb:DeleteItem
          Resource:
            Fn::Sub: "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Cities"

functions:
  status:
    handler: src/handler.status
    events:
      - http:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    events:
      - http:
          path: /item
          method: post
  fetchItems:
    handler: src/fetchItems.handler
    events:
      - http:
          path: /items
          method: get
  getItem:
    handler: src/getItem.handler
    events:
      - http:
          path: /items/{Cidade}
          method: get     
  updateItem:
    handler: src/updateItem.handler
    events:
      - http:
          path: /items/{Cidade}
          method: put      
  deleteItem:
    handler: src/deleteItem.handler
    events:
      - http:
          path: /items/{Cidade}
          method: delete

resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Cities
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - 
            AttributeName: "Cidade"
            AttributeType: "S"
        KeySchema:
          - 
            AttributeName: "Cidade"
            KeyType: "HASH"
